使用numpy实现梯度下降 示例1

In [ ]:
import numpy as np
from random import shuffle

def sigmoid(x):
    return 1/(1+np.exp(-x))

# 二值交叉熵
def BCE_loss(y_gt,y_pred):
    pass



def main():
    pass


if __name__=='__main__':
    main()



In [5]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
print(a,type(a))
# np.matrix的用法不推荐，可能被remove
# https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
# b=np.matrix(a)
b=np.array(a)
print(b,type(b))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] <class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
