用来记录一些numpy的随机数操作

In [4]:
import numpy as np
# 打印范围内的随机整数，
np.random.seed(2222)
print('randint:\n',np.random.randint(1,10,(4,4)))

randint:
 [[2 6 8 1]
 [1 8 7 6]
 [6 3 3 6]
 [2 4 5 8]]
uniform:
 [[8.07949138 2.37214156 7.54019823 2.5598809 ]
 [5.09572952 4.54629606 9.59168317 6.20557938]
 [9.28686819 6.69410049 1.87796213 3.19344596]
 [9.25109243 7.66875118 3.67416537 3.19554192]]
[[0.09920694 0.17318795 0.11420984 0.08302919]
 [0.17143073 0.93094947 0.36059996 0.09266486]
 [0.82636121 0.35136712 0.14105796 0.78801245]
 [0.5313128  0.84625043 0.17935904 0.14440943]]


In [ ]:
import numpy as np
# 打印范围内的随机小数
np.random.seed(2222)
print('uniform:\n',np.random.uniform(1,10,(4,4)))

In [5]:
import numpy as np
#[0,1)范围内的随机数
np.random.seed(2222)
print(np.random.random((4,4)))

[[0.02241385 0.62701852 0.91942832 0.39493572]
 [0.82975512 0.55458911 0.46507489 0.47675339]
 [0.06602558 0.1965233  0.53609115 0.74918278]
 [0.82577245 0.64388717 0.54649585 0.87074059]]


In [101]:
import numpy as np
# 从中选择一个
# np.random.seed(2222)
print('choice:',np.random.choice(['a','b','b','d'],3))

choice: ['b' 'd' 'a']


In [40]:
import numpy as np
# 根据给定的形状获得随机数
# 服从正态分布
np.random.seed(2222)
print('randn:',np.random.randn(1,2,3))

randn: [[[-0.94079146  1.01295397  0.46458472]
  [ 0.71528586  0.5497356  -1.22573198]]]


In [47]:
import numpy as np
# 根据给定的形状获得[0,1)之间的随机数
np.random.seed(2222)
print('rand:',np.random.rand(1,2,3))

randn: [[[0.72720018 0.28898549 0.84958831]
  [0.72706081 0.20943945 0.63031518]]]
